# Default values for github-actions-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/curium-rocks/ubuntu-actions-runner
  pullPolicy: IfNotPresent
  tag: "2a56fb140a42cc727cfafb8286cc265d504c7f68"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  annotations: {}
  name: ""
organizationUrl: ~
enterpriseUrl: ~
runnerRepoUrl: ~
runnerLabels: 
  - self-hosted
  - linux
  - ubuntu
  - k8s
token:
  secretName: github-token
  secretKeyName: token
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
