# Default values for github-actions-runner.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: ghcr.io/curium-rocks/centos-actions-runner
  pullPolicy: IfNotPresent
  tag: "539bed3615a775ab3617d8ea322fbdc57c28f26d"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  annotations: {}
  name: ""
organizationUrl: ~
enterpriseUrl: ~
runnerRepoUrl: ~
token:
  secretName: github-token
  secretKeyName: token
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
nodeSelector: {}
tolerations: []
affinity: {}
