name: Release Charts
on:
  push:
    branches:
      - main
    paths:
      - "charts/**"
      - ".github/release.yaml"
jobs:
  release:
    name: 'Helm'
    uses: curium-rocks/flows/.github/workflows/helm-release.yml@main
